{
    "name": "CAS Advanced Correspondence",
    "summary": "Official templates, inbound/outbound registry, immutable PDFs and auditable signatures",
    "version": "19.0.1.0.0",
    "category": "Productivity",
    "author": "Chodan Ara Shomal",
    "website": "https://erp.chodanara.com",
    "license": "LGPL-3",
    "depends": ["cas_correspondence", "cas_document_core"],
    "data": [
        "security/cas_correspondence_advanced_security.xml",
        "security/ir.model.access.csv",
        "data/cas_correspondence_advanced_sequence.xml",
        "reports/correspondence_report.xml",
        "views/correspondence_template_views.xml",
        "views/correspondence_register_views.xml",
        "views/correspondence_letter_views.xml",
        "views/correspondence_signature_views.xml",
        "views/correspondence_advanced_menus.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
