{
    "name": "CAS Document Core",
    "summary": "Secure, versioned organizational document foundation with pluggable storage",
    "version": "19.0.1.0.0",
    "category": "Productivity/Documents",
    "author": "Chodan Ara Shomal",
    "website": "https://erp.chodanara.com",
    "license": "LGPL-3",
    "depends": ["mail"],
    "data": [
        "security/cas_document_security.xml",
        "security/ir.model.access.csv",
        "data/cas_document_sequence.xml",
        "data/cas_document_cron.xml",
        "views/cas_document_backend_views.xml",
        "views/cas_document_folder_views.xml",
        "views/cas_document_views.xml",
        "views/cas_document_ocr_views.xml",
        "wizard/upload_version_wizard_views.xml",
        "views/cas_document_menus.xml",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
}
